-- Customize Mason
---@type LazySpec
return {
  -- use mason-tool-installer for automatically installing Mason packages
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    -- overrides `require("mason-tool-installer").setup(...)`
    opts = {
      -- Make sure to use the names found in `:Mason`
      ensure_installed = {
        "astro-language-server",
        "bash-language-server",
        "bazelrc-lsp",
        "buf",
        "clj-kondo",
        "clojure-lsp",
        "codespell",
        "debugpy",
        "delve",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "editorconfig-checker",
        "gofumpt",
        "semgrep",
        "snyk",
        "golangci-lint",
        "golines",
        "gomodifytags",
        "gopls",
        "gotests",
        "gradle-language-server",
        "helm-ls",
        "iferr",
        "impl",
        "jq",
        "json-lsp",
        "json-to-struct",
        "kotlin-language-server",
        "lua-language-server",
        "marksman",
        "misspell",
        "rust-analyzer",
        "selene",
        "shellcheck",
        "shfmt",
        "sqlfmt",
        "staticcheck",
        "stylua",
        "systemdlint",
        "terraform-ls",
        "tex-fmt",
        "tree-sitter-cli",
        "vim-language-server",
        "vint",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
