-- Customize Treesitter
---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "clojure",
      "cmake",
      "comment",
      "cpp",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "groovy",
      "hcl",
      "java",
      "javascript",
      "json",
      "kotlin",
      "latex",
      "lua",
      "make",
      "perl",
      "python",
      "ruby",
      "rust",
      "scala",
      "sql",
      "terraform",
      "todotxt",
      "typescript",
      "vue",
      "vim",
      "yaml",
    },
  },
}
